id: A94BB30BC
title: Prayer for the Long Life of Yangthang Rinpoche, Kunzang Jikmé Dechen Ösal Dorjé
type: translation
pechas:
- IA9FD38F9
- I914D8CBA
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:37:34.782191
  last_modified_at: 2023-01-04 11:37:34.782204
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IA9FD38F9/4477: 4D50
  I914D8CBA/1194: 4D50
